fruits=[]
f1=input("enter 1st data : ")
fruits.append(f1)
f2=input("enter 2nd data : ")
fruits.append(f2)
f3=input("enter 3rd data : ")
fruits.append(f3)
f4=input("enter 4th data : ")
fruits.append(f4)
f5=input("enter 5th data : ")
fruits.append(f5)
f6=input("enter 6th data : ")
fruits.append(f6)
f7=input("enter 7th data : ")
fruits.append(f7)
print(fruits)